SELECT AIN.ANIMAL_ID, AIN.ANIMAL_TYPE, AIN.NAME
FROM ANIMAL_INS AIN LEFT OUTER JOIN ANIMAL_OUTS AOUT
ON (AIN.ANIMAL_ID = AOUT.ANIMAL_ID)
WHERE SUBSTR(AIN.SEX_UPON_INTAKE, 1, 6) = 'Intact'
AND SUBSTR(AOUT.SEX_UPON_OUTCOME, 1, 6) != 'Intact'
