-- 코드를 입력하세요
SELECT TO_CHAR(DATETIME, 'HH24') "HOUR", COUNT(*) "COUNT" 
FROM ANIMAL_OUTS 
WHERE TO_CHAR(DATETIME, 'HH24') >= '09'AND TO_CHAR(DATETIME, 'HH24') < '20'
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY TO_CHAR(DATETIME, 'HH24');