-- 질문하기 참고
-- A : ANIMAL_OUTS
-- B : HOUR
SELECT B.HH, COUNT(A.HOUR)
    FROM (SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR
        FROM ANIMAL_OUTS) A
    RIGHT OUTER JOIN
        (SELECT LEVEL-1 AS HH FROM DUAL CONNECT BY LEVEL <= 24) B
    ON A.HOUR = B.HH
    GROUP BY B.HH
    ORDER BY B.HH