SELECT A.HOUR, COUNT(O.DATETIME)
FROM (
    SELECT LEVEL-1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) A LEFT OUTER JOIN ANIMAL_OUTS O
ON A.HOUR = TO_CHAR(O.DATETIME, 'HH24')
GROUP BY A.HOUR
ORDER BY A.HOUR;