-- 코드를 입력하세요
SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) as "HOUR", COUNT(*) as "COUNT"
FROM ANIMAL_OUTS
GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
--조건을 19를 주지 않으면 값으로는 똑같이 나오지만 조건과 다르기 때문에 틀린 결과 값이라고 나온다.
HAVING EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) BETWEEN 9 AND 19
ORDER BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP));