-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
    from ANIMAL_INS i, ANIMAL_OUTS o
    where i.ANIMAL_ID = o.ANIMAL_ID
    and i.SEX_UPON_INTAKE <> o.SEX_UPON_OUTCOME
    ORDER BY i.ANIMAL_ID;
