-- 코드를 입력하세요
SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR, count(*) 
FROM ANIMAL_OUTS
group by EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
having EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) between 9 and 19
order by EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP));
    